// <auto-generated />
using System;
using F1Telemetry.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace F1Telemetry.Infrastructure.Migrations
{
    [DbContext(typeof(F1TelemetryDbContext))]
    [Migration("20260929004842_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("F1Telemetry.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("DriverNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DriverNumber"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DriverNumber");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("F1Telemetry.Domain.Entities.LapTime", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer");

                    b.Property<double>("LapDurationMs")
                        .HasColumnType("double precision");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverNumber");

                    b.HasIndex("SessionKey");

                    b.ToTable("LapTimes");
                });

            modelBuilder.Entity("F1Telemetry.Domain.Entities.PitStop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DriverNumber")
                        .HasColumnType("integer");

                    b.Property<int>("LapNumber")
                        .HasColumnType("integer");

                    b.Property<double>("PitDurationMs")
                        .HasColumnType("double precision");

                    b.Property<int>("SessionKey")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverNumber");

                    b.HasIndex("SessionKey");

                    b.ToTable("PitStops");
                });

            modelBuilder.Entity("F1Telemetry.Domain.Entities.Session", b =>
                {
                    b.Property<int>("SessionKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionKey"));

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MeetingKey")
                        .HasColumnType("integer");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SessionKey");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("F1Telemetry.Domain.Entities.LapTime", b =>
                {
                    b.HasOne("F1Telemetry.Domain.Entities.Driver", "Driver")
                        .WithMany("LapTimes")
                        .HasForeignKey("DriverNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Telemetry.Domain.Entities.Session", "Session")
                        .WithMany("LapTimes")
                        .HasForeignKey("SessionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("F1Telemetry.Domain.Entities.PitStop", b =>
                {
                    b.HasOne("F1Telemetry.Domain.Entities.Driver", "Driver")
                        .WithMany("PitStops")
                        .HasForeignKey("DriverNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("F1Telemetry.Domain.Entities.Session", "Session")
                        .WithMany("PitStops")
                        .HasForeignKey("SessionKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("F1Telemetry.Domain.Entities.Driver", b =>
                {
                    b.Navigation("LapTimes");

                    b.Navigation("PitStops");
                });

            modelBuilder.Entity("F1Telemetry.Domain.Entities.Session", b =>
                {
                    b.Navigation("LapTimes");

                    b.Navigation("PitStops");
                });
#pragma warning restore 612, 618
        }
    }
}
